# Generated by Django 2.2 on 2021-04-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idealer', '0004_add_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_adds', to='idealer.User'),
        ),
    ]
